#!/bin/sh
prj_dir=`pwd $DIRNAME`
jdk_home="/home/kmagalhaes/Development/java/jdk1.8.0_51"
main="$prj_dir/bin/payara-micro-4.1.1.154.jar"

./mvnw clean install -Ppayara
$jdk_home/bin/java -jar $main --noCluster --port 9000 --name payara-spring-boot --deploy $prj_dir/target/payara-spring-boot.war